// 아이콘 이름을 문자열로 정의 (서버 컴포넌트에서 클라이언트 컴포넌트로 전달 가능)
export type IconName = 'CalendarClock' | 'BarChart3' | 'FileText' | 'BookOpen' | 'Palette' | 'Image' | 'LayoutDashboard' | 'BrainCircuit' | null;
export type SolutionCategory = 'Construction' | 'General' | 'Academic' | 'Architecture' | 'Construction / Digital Twin / RAG' | 'Construction / RAG' | 'Safety';

export interface Solution {
    id: string;
    title: string;
    description: string;
    description2?: string;
    href: string;
    icon: IconName;
    external: boolean;
    category: SolutionCategory;
    image?: string;
    hasSpecialEffect?: boolean;
    isNew?: boolean;
    titleColor?: string;
}

export const simpleSolutions: Solution[] = [
    {
        id: 'solution-safetron',
        title: 'Safetron AI',
        description: '건설 안전 지식그래프 탐색 · AI 사고 패턴 분석 대시보드',
        description2: '38,000건 이상의 건설 사고 데이터를 3D 지식그래프로 시각화하고, AI 기반 사고 패턴 분석·시공사 프로파일링·교차 분석·안전교육 콘텐츠를 제공하는 건설 안전 인텔리전스 플랫폼입니다.',
        href: '/safetron/',
        icon: 'BarChart3',
        external: false,
        category: 'Safety',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-aura-clinic',
        title: 'Aura Clinic AI Web App',
        description: '성형외과 가상 홈페이지 및 AI 뷰티 시뮬레이션',
        description2: '사진 한 장으로 시술 전후를 실시간 시뮬레이션하고, 9개국어 지원 AI 상담 시스템과 600페이지 이상의 전문 임상 지식을 제공하는 프리미엄 병원 웹사이트입니다.',
        href: 'https://tanggle.vercel.app/',
        icon: 'BrainCircuit',
        external: true,
        category: 'General',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-youtube-graber',
        title: 'Premium YouTube Grab',
        description: '빠르고 안전한 유튜브 미디어 다운로더',
        description2: '자체 개발(yt-dlp 기반)한 무광고 유튜브 영상 및 음원 추출기. 외부 툴의 한계를 벗어나 고화질 다운로드와 FFmpeg 병합을 통해 안정적인 고음질 음원을 제공합니다.',
        href: '/youtube-grab/',
        icon: 'Image',
        external: true,
        category: 'General',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-posteval-ai',
        title: 'Post Evaluation Report AI',
        description: '건설공사 사후평가서를 AI가 자동으로 작성합니다.',
        description2: 'RAG 파이프라인으로 16개 PDF를 분석, 47개 필드를 자동 추출. Gemini AI + MySQL 벡터 검색 기반.',
        href: 'https://posteval.ninetynine99.co.kr/landing',
        icon: 'FileText',
        external: true,
        category: 'Construction / RAG',
        hasSpecialEffect: true,
        isNew: true,

    },
    {
        id: 'solution-repair-insight-law',
        title: 'Repair Insight Law',
        description: '119건 건설하자 판결문 AI 분석 · RAG 기반 법리 검색 시스템',
        description2: '실제 법원 판결문 119건을 Gemini AI가 학습. 벡터 임베딩 기반 유사 판례 검색, 책임제한비율 분석, 17개 통계 차트 대시보드를 제공하는 건설하자 분쟁 전문 AI.',
        href: '/repair_insight_law',
        icon: 'BarChart3',
        external: false,
        category: 'Construction / RAG',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-prompt-analyzer',
        title: 'Prompt Analyzer & Optimizer',
        description: '프롬프트를 분석·평가하고 최적의 개선안을 제시합니다.',
        description2: 'AI 프롬프트의 명확성, 구조, 맥락 완성도를 다각도로 평가하고, 더 나은 결과를 이끌어내는 개선된 프롬프트를 자동 생성합니다.',
        href: 'https://prompt-analyzer-danny-chos-projects.vercel.app/',
        icon: 'BrainCircuit',
        external: true,
        category: 'General',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-thesis-advisor',
        title: 'Academic Advisor in Architecture',
        description: '건축학 논문 자동 심사 AI 시스템 (89편 학습, 50개 항목, 60초 분석)',
        description2: 'React + FastAPI + ChromaDB RAG 엔진으로 89편 논문 학습. 50개 심사 항목을 60초 내 자동 평가 — 연구방법론부터 결론까지 전문 심사위원 수준의 피드백 제공.',
        href: '/thesis-advisor/',
        icon: 'BookOpen',
        external: false,
        category: 'Academic',
        hasSpecialEffect: true,
        isNew: true,
    },

    {
        id: 'solution-html-merger',
        title: 'HTML Merger',
        description: '여러 HTML 파일을 구조·형식·콘텐츠를 유지하며 하나로 병합합니다.',
        description2: '드래그 앤 드롭으로 업로드하면 CSS 충돌 없이 안전하게 병합. 내비게이션 포함, 단일 파일로 바로 사용 가능!',
        href: 'https://html-merger-v1-0-u9ln.vercel.app/',
        icon: 'FileText',
        external: true,
        category: 'General',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-class-ai',
        title: 'Class AI',
        description: 'PDF 한 장이면 자료 검색, 연습문제, 시험 출제, 강의 노트, 리포트 가이드까지.',
        description2: 'ClassAI의 RAG 엔진이 당신의 강의를 지능형 학습 플랫폼으로 변환합니다.',
        href: 'https://260219aiclass.vercel.app/landing.html#',
        icon: 'BookOpen',
        external: true,
        category: 'Academic',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-haema-architect',
        title: 'Haema Architect',
        description: 'AI 기반 건축 법규 검토 및 3D 매스 자동 생성 시스템',
        description2: 'VWorld GIS 연동 대지분석, 26+ 건축법규 AI 종합분석(4배치 드릴다운), 토지이용규제 조례분석, Three.js 기반 3D 매스 시각화까지 원스톱으로 제공합니다.',
        href: 'https://www.ninetynine99.co.kr/haema',
        icon: 'LayoutDashboard',
        external: true,
        category: 'Architecture',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-ai-pmis',
        title: 'AI-PMIS',
        description: '건설사업 모든 데이터를 Data Cube로 가공하고 AI가 답변합니다.',
        description2: 'EVMS 기반 원가·공정·자재·조직 통합 관리와 AI 자연어 질의를 하나의 대시보드에서 경험하세요.',
        href: 'https://ai-pmis.vercel.app/',
        icon: 'LayoutDashboard',
        external: true,
        category: 'Construction',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-25',
        title: 'ARCHI RENDER',
        description: 'AI 기반 건축 스케치 → 3D 렌더링 & 시네마틱 영상 생성 도구',
        description2: '건축 스케치 한 장을 업로드하면 AI가 고품질 3D 렌더링으로 변환하고, 시네마틱 워크쓰루 영상까지 자동 생성하는 올인원 건축 시각화 솔루션입니다.',
        href: 'https://archi-render-eta.vercel.app/',
        icon: 'Image',
        external: true,
        category: 'Architecture',
        hasSpecialEffect: true,
        isNew: true,
    },
    {
        id: 'solution-24',
        title: 'Smart Remodeling AI',
        description: 'AI 기반 인테리어 리모델링 시뮬레이션',
        description2: '사진 한 장으로 11가지 인테리어 스타일을 즉시 변환하고, 재질 시뮬레이션, Flash 에디팅, 2D 평면도 추출, 시네마틱 룸투어 영상까지 생성하는 올인원 AI 리모델링 솔루션입니다.',
        href: 'https://smart-remodeling.vercel.app',
        icon: 'Image',
        external: true,
        category: 'Architecture',
        hasSpecialEffect: true,
    },
    {
        id: 'solution-consafe-v2',
        title: 'ConSafe Insight',
        description: '건설현장 위험요인 AI 분석',
        description2: '산업안전보건법 기준에 맞춰 건설현장 사진을 실시간 분석하고, 위험 등급과 개선 대책을 제시하는 AI 기반 안전 관리 솔루션입니다.',
        href: 'https://consafe-insight2-git-main-danny-chos-projects.vercel.app/',
        icon: 'BrainCircuit',
        external: true,
        category: 'Safety',
        image: '/solutions/consafe-insight.png',
        hasSpecialEffect: true,
    },
    {
        id: 'solution-01',
        title: 'Smart Construction Duration Estimator',
        description: 'AI 기반 적정공기 산정 Agent',
        description2: '국토부 적정 공사기간 가이드라인과 통계자료 기반 머신러닝 기법을 활용한 최적의 적정공기 예측',
        href: '/smart-duration-estimator',
        icon: 'CalendarClock',
        external: false,
        category: 'Construction',
    },
    {
        id: 'solution-02',
        title: 'AI Maturity & Productivity Surge Matrix',
        description: '건설 AI 성숙도 및 생산성 분석 대시보드',
        description2: '11단계 AI 활용 로드맵과 생산성 변화를 시각화한 전략 분석 도구',
        href: '/ai-maturity-dashboard',
        icon: 'BarChart3',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-03',
        title: 'Peer Reviewer for Academic Paper',
        description: '논문 검토 및 피드백 AI Agent',
        description2: '건설 분야 박사학위 논문을 SCI급 저널 게재 기준에 맞춰 철저히 검토하고 구체적인 수정 방안을 제시',
        href: '/peer-reviewer',
        icon: 'FileText',
        external: false,
        category: 'Academic',
    },
    {
        id: 'solution-04',
        title: 'Pocket E-Book Creator',
        description: '역동적이고 살아 있는 E-Book으로',
        description2: '수백 페이지의 기술 보고서, 이제 주머니 속 인터랙티브 대시보드로 휴대하십시오. Pocket Book Creator는 복잡한 콘텐츠를 살아있는 인사이트로 변환하는 \'디지털 연금술\'입니다.',
        href: '/pocket-ebook-creator',
        icon: 'BookOpen',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-05',
        title: 'Web Design Palette Generator',
        description: '웹 디자인 색상 팔레트 생성 도구',
        description2: '브랜드 톤에 맞춘 컬러 시스템과 코드 스니펫을 한 번에. 미니멀, 다크, 럭셔리 등 20+ 테마를 선택하고 바로 적용하세요.',
        href: '/web-design-palette-generator/index.html',
        icon: 'Palette',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-06',
        title: 'Instagram Photo Gen Pro',
        description: '회사 홍보용 이미지 자동 생성 도구',
        description2: 'AI 기반으로 회사 홍보용 인스타그램 이미지를 자동으로 생성하는 전문 도구입니다.',
        href: '/instagram-photo-gen/index.html',
        icon: 'Image',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-08',
        title: 'Construction Safety Analyzer',
        description: '건설 현장 안전 분석 AI Agent',
        description2: '현장 사진을 업로드하면 AI가 잠재적 위험요인을 자동으로 분석하고 상세한 안전 보고서를 생성합니다.',
        href: '/construction-safety-analyzer/index.html',
        icon: 'FileText',
        external: false,
        category: 'Safety',
    },
    {
        id: 'solution-09',
        title: 'InfoGenius Vision',
        description: 'AI 인포그래픽 생성기',
        description2: '실시간 데이터 검증과 Google 검색을 기반으로 고품질 인포그래픽을 생성하는 전문 AI 시각화 도구입니다.',
        href: 'https://aistudio.google.com/app/apps/drive/1juyNvyWJLuc_bFQyugzn7MrtbiftId7q?showPreview=true&showAssistant=true&fullscreenApplet=true',
        icon: 'Image',
        external: true,
        category: 'General',
    },
    {
        id: 'solution-10',
        title: 'Construction Field Safety Guardian',
        description: '건설현장 실시간 안전지킴이 AI 챗봇',
        description2: '30000건 사건사고DB 기반 실시간 멀티모달 분석, 60개국 다국어 지원, Golden Time을 지키는 긴급 위기대응 시스템, TBM 교육자료 제공',
        href: 'https://www.youtube.com/watch?v=gQ2bZJ318-Q',
        icon: 'FileText',
        external: true,
        category: 'Safety',
    },
    {
        id: 'solution-11',
        title: 'Construction Cost Analysis AI',
        description: '건설 내역 분석 전문가',
        description2: '4분할 레이아웃으로 CSV 데이터를 실시간 분석. AI 채팅으로 공종별, 동별 상세 분석과 핵심 지표를 시각화하여 즉각 제공하는 전문가용 건설 내역 분석 도구',
        href: '/construction-cost-chatbot/index.html',
        icon: 'BarChart3',
        external: false,
        category: 'Construction',
    },
    {
        id: 'solution-12',
        title: 'CM Proposal Orchestrator AI',
        description: 'AI-Powered Proposal Orchestrator',
        description2: '건설사업관리 제안서 작성을 자동화하는 AI 시스템입니다. 20만 건의 데이터셋을 기반으로 최적의 제안 컨텐츠를 생성합니다.',
        href: '/proposal-system',
        icon: 'FileText',
        external: false,
        category: 'Construction',
    },
    {
        id: 'solution-13',
        title: 'AI Scanner Pro',
        description: '명함 자동 추출 스마트 관리 도구',
        description2: '최신 Gemini AI 기술을 활용하여 명함에서 이름, 연락처, 회사명 등 핵심 정보를 자동으로 추출하는 스마트 관리 도구입니다.',
        href: '/bizcard-scanner-pro',
        icon: 'FileText',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-14',
        title: 'Public Building Cost Dashboard',
        description: '공공청사 공사비 분석 통합 대시보드',
        description2: '공공청사 건설 공사비의 통계 분석, EDA, 회귀분석 및 머신러닝 기반 공사비 예측 시뮬레이션을 제공하는 통합 데이터 분석 플랫폼입니다.',
        href: '/cost-prediction-dashboard',
        icon: 'BarChart3',
        external: false,
        category: 'Construction',
    },
    {
        id: 'solution-15',
        title: 'AI Insight Newsletter',
        description: '최신 AI 트렌드 및 기술 뉴스레터',
        description2: '정기적으로 발행되는 AI 기술 트렌드와 인사이트 뉴스레터 아카이브입니다. 과거 발행된 모든 뉴스레터를 한눈에 확인하세요.',
        href: '/ai-newsletter',
        icon: 'BookOpen',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-16',
        title: 'AI Academic Hub',
        description: 'AI & 건설 산업 학습 아카이브',
        description2: 'AI가 바꾸는 건설산업의 미래와 최신 기술 트렌드를 심층적으로 학습할 수 있는 전문 교육 자료 라이브러리입니다.',
        href: '/academic-hub',
        icon: 'BookOpen',
        external: false,
        category: 'Academic',
    },
    {
        id: 'solution-17',
        title: 'AI Safety Document Chatbot (RAG)',
        description: '안전 관리 문서 기반 RAG AI 챗봇',
        description2: 'PDF 안전 가이드 및 매뉴얼을 업로드하면 AI가 학습하여 실시간으로 답변하는 지능형 안전 관리 시스템. Vertex AI 기반의 정교한 RAG(검색 증강 생성) 기술 적용.',
        href: '/safety-chatbot',
        icon: 'FileText',
        external: false,
        category: 'Safety',
    },
    {
        id: 'solution-18',
        title: 'AI Safety Insight Dashboard (RAG)',
        description: '2만여 건의 국가 건설 사고 데이터를 정밀 분석하는 지능형 대시보드.',
        description2: 'WBS-RBS 기반 위험정보 모니터링 및 지능형 RAG 엔진을 통한 실시간 안전 대책 제시 시스템.',
        href: 'https://safety.ninetynine99.co.kr',
        icon: 'BarChart3',
        external: true,
        category: 'Safety',
    },
    {
        id: 'solution-21',
        title: 'AI Website Builder',
        description: '누구나 쉽게 만드는 커스텀 홈페이지 제작',
        description2: '복잡한 코딩 없이, 대화와 아이디어만으로 전문적인 웹사이트를 구축하세요. 디자인부터 배포까지 AI가 당신의 상상을 현실로 만듭니다.',
        href: '/website-builder',
        icon: 'LayoutDashboard',
        external: false,
        category: 'General',
    },
    {
        id: 'solution-22',
        title: 'Statistical Analysis Studio',
        description: 'AI 기반 통계 분석 자동화 플랫폼',
        description2: 'CSV 데이터를 업로드하면 기술통계, 상관분석, 회귀분석(OLS), 파레토 분석, 교차분석, 이상치 탐지까지 자동으로 수행하여 학술 수준의 분석 보고서를 생성합니다.',
        href: '/stat/',
        icon: 'BarChart3',
        external: false,
        category: 'Academic',
    },
    {
        id: 'solution-23',
        title: "Danny's BridgeBook",
        description: 'AI 기반 인맥 네트워킹 관리 도구',
        description2: 'Gemini AI를 활용한 스마트 인맥 관리 시스템. CSV 데이터를 기반으로 인맥 네트워크를 체계적으로 관리하고, AI 분석을 통해 관계 강화 전략과 네트워킹 인사이트를 제공합니다.',
        href: '/bridgebook/',
        icon: 'BookOpen',
        external: false,
        category: 'General',
    },
];
